name: Throughput Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_and_test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
          - name: Linux-arm
            os: ubuntu-24.04-arm
          - name: macOS
            os: macos-latest
          - name: Windows
            os: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: KFR Throughput Test
        shell: bash
        run: python -u benchmark/throughput.py 5 25 kfr

      - name: FFTW3 Throughput Test
        shell: bash
        run: python -u benchmark/throughput.py 5 25 fftw3

      - name: pffft Throughput Test
        if: ${{ runner.os != 'Windows' }}
        shell: bash
        run: python -u benchmark/throughput.py 5 25 pffft

      - name: simd_low_order_opt1 Throughput Test
        shell: bash
        run: python -u benchmark/throughput.py 5 25 simd_low_order_opt1

      - name: simd_low_order_opt2 Throughput Test
        shell: bash
        run: python -u benchmark/throughput.py 5 25 simd_low_order_opt2