name: Throughput Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_and_test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
          - name: macOS
            os: macos-latest
          - name: Windows
            os: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Show CPU Info (Linux)
        if: runner.os == 'Linux'
        run: lscpu

      - name: Show CPU Info (macOS)
        if: runner.os == 'macOS'
        run: sysctl -n machdep.cpu.brand_string

      - name: Show CPU Info (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: Get-CimInstance -ClassName Win32_Processor | Select-Object Name, NumberOfCores, NumberOfLogicalProcessors

      - name: Install IPP (Linux)
        if: runner.os == 'Linux'
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update && sudo apt install intel-oneapi-ipp-devel

      - name: Install IPP (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          nuget install intelipp.static.win-x64 -Version 2022.3.0.387

      - name: IPP Throughput Test (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          source /opt/intel/oneapi/setvars.sh
          python -u benchmark/throughput.py 5 25 ipp

      - name: IPP Throughput Test (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          python -u benchmark/throughput.py 5 25 ipp

      - name: KFR Throughput Test
        shell: bash
        run: python -u benchmark/throughput.py 5 25 kfr

      - name: FFTW3 Throughput Test
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: python -u benchmark/throughput.py 5 25 fftw3

      - name: FFTW3 Estimate Throughput Test
        shell: bash
        run: python -u benchmark/throughput.py 5 25 fftw3_estimate

      - name: pffft Throughput Test
        if: ${{ runner.os != 'Windows' }}
        shell: bash
        run: python -u benchmark/throughput.py 5 25 pffft

      - name: simd_low_order_opt1 Throughput Test
        shell: bash
        run: python -u benchmark/throughput.py 5 25 simd_low_order_opt1

      - name: simd_low_order_opt2 Throughput Test
        shell: bash
        run: python -u benchmark/throughput.py 5 25 simd_low_order_opt2